"""Single source of truth for local service names, ports, and proxy config."""
from __future__ import annotations
from dataclasses import dataclass, asdict
from typing import Mapping
from urllib.parse import urlsplit
from pathlib import Path
import hashlib
import ipaddress
import json
import os
import re
import yaml

_HOSTNAME_RE = re.compile(r"^[a-z0-9](?:[a-z0-9.-]{0,251}[a-z0-9])?\.test$")
_TRUST_DOMAINS = {"operator", "production", "commons", "quarantine", "deception", "witness"}

@dataclass(frozen=True)
class Service:
    name: str
    hostname: str
    upstream: str
    port: int
    health_path: str = "/health"
    trust_domain: str = "production"
    enabled: bool = True

    def validate(self) -> None:
        if not self.name or not _HOSTNAME_RE.fullmatch(self.hostname):
            raise ValueError("service names must use the reserved .test namespace")
        parsed = urlsplit("//" + self.upstream)
        if not parsed.hostname or not parsed.port or parsed.port != self.port:
            raise ValueError(f"upstream/port mismatch for {self.name}")
        try:
            if not ipaddress.ip_address(parsed.hostname).is_loopback:
                raise ValueError(f"upstream for {self.name} must be loopback")
        except ValueError as exc:
            raise ValueError(f"invalid loopback upstream for {self.name}") from exc
        if not 1 <= self.port <= 65535:
            raise ValueError("service port is outside TCP range")
        if not self.health_path.startswith("/") or any(ch in self.health_path for ch in "\r\n"):
            raise ValueError(f"invalid health path for {self.name}")
        if self.trust_domain not in _TRUST_DOMAINS:
            raise ValueError(f"invalid trust domain for {self.name}")

class ServiceRegistry:
    def __init__(self, services: Mapping[str, Mapping], *, reverse_proxy_port: int = 80):
        self.reverse_proxy_port=int(reverse_proxy_port)
        if not 1 <= self.reverse_proxy_port <= 65535: raise ValueError("invalid reverse proxy port")
        self.services = {
            name: Service(
                name=name,
                hostname=str(item["hostname"]),
                upstream=str(item["upstream"]),
                port=int(item.get("port") or urlsplit("//" + str(item["upstream"])).port),
                health_path=str(item.get("health_path") or "/health"),
                trust_domain=str(item.get("trust_domain") or "production"),
                enabled=bool(item.get("enabled", True)),
            )
            for name, item in services.items()
            if name != "reverse_proxy"
        }
        if not self.services: raise ValueError("service registry cannot be empty")
        for service in self.services.values(): service.validate()
        ports=[s.port for s in self.services.values()]
        if len(ports)!=len(set(ports)): raise ValueError("service ports must be unique")
        hosts=[s.hostname for s in self.services.values()]
        if len(hosts)!=len(set(hosts)): raise ValueError("service hostnames must be unique")
    def snapshot(self): return {name:asdict(service) for name,service in self.services.items()}
    def hosts_entries(self, address="127.0.0.1"):
        return "# Generated by BEAST; do not edit.\n" + "\n".join(
            f"{address} {service.hostname}" for service in self.services.values() if service.enabled
        ) + "\n"
    def nginx_config(self):
        blocks=[]
        for service in self.services.values():
            if not service.enabled:
                continue
            blocks.append(
                f"server {{\n"
                f"    listen {self.reverse_proxy_port};\n"
                f"    server_name {service.hostname};\n"
                "    server_tokens off;\n"
                "    location / {\n"
                f"        proxy_pass http://{service.upstream};\n"
                "        proxy_set_header Host $host;\n"
                "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
                "        proxy_set_header X-Forwarded-Proto $scheme;\n"
                "        proxy_connect_timeout 5s;\n"
                "        proxy_read_timeout 60s;\n"
                "    }\n"
                "}"
            )
        return "# Generated by BEAST; do not edit.\n" + "\n\n".join(blocks)+"\n"

    def resolve(self, hostname: str) -> Service:
        for service in self.services.values():
            if service.hostname == hostname: return service
        raise KeyError(f"unknown service hostname: {hostname}")

    def health_contract(self) -> dict:
        return {
            name: {
                "hostname": item.hostname,
                "upstream": item.upstream,
                "health_url": f"http://{item.upstream}{item.health_path}",
                "trust_domain": item.trust_domain,
                "enabled": item.enabled,
                "status": "unprobed" if item.enabled else "disabled",
            }
            for name, item in self.services.items()
        }

    @classmethod
    def from_file(cls, path: str | Path) -> "ServiceRegistry":
        payload=yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
        services=payload.get("services") or {}
        proxy=services.get("reverse_proxy") or {}
        return cls(services,reverse_proxy_port=int(proxy.get("port") or 80))

    def digest(self) -> str:
        body={"reverse_proxy_port":self.reverse_proxy_port,"services":self.snapshot()}
        return "sha256:"+hashlib.sha256(json.dumps(body,sort_keys=True,separators=(",",":")).encode()).hexdigest()

    def render(self, output_dir: str | Path) -> dict:
        root=Path(output_dir); root.mkdir(parents=True,exist_ok=True)
        outputs={"hosts":root/"hosts.generated","nginx":root/"nginx.generated.conf"}
        for key,path in outputs.items():
            content=self.hosts_entries() if key=="hosts" else self.nginx_config()
            temp=path.with_suffix(path.suffix+".tmp")
            temp.write_text(content,encoding="utf-8"); os.replace(temp,path)
        return {key:str(path) for key,path in outputs.items()}
