"""Health-gated local DNS/proxy publication and signed node DNS records.

The module deliberately writes only a generated staging directory.  An
operator may point a DNS/proxy daemon at that directory or promote the files
with its normal configuration-management process; an unhealthy lease can
never be rendered into a public record.
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import tempfile
import time
from urllib.error import URLError
from urllib.request import ProxyHandler, build_opener
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Mapping

from app.kernel.networking.service_registry import ServiceRegistry


def _canonical(value: Mapping[str, Any]) -> bytes:
    return json.dumps(dict(value), sort_keys=True, separators=(",", ":")).encode("utf-8")


def _digest(value: Mapping[str, Any]) -> str:
    return "sha256:" + hashlib.sha256(_canonical(value)).hexdigest()


def _atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, candidate = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(candidate, 0o640)
        os.replace(candidate, path)
    finally:
        if os.path.exists(candidate):
            os.unlink(candidate)


@dataclass(frozen=True)
class NodeDnsAdvertisement:
    node_id: str
    hostname: str
    address: str
    port: int
    attestation_digest: str
    expires_at: int
    key_id: str
    public_key: str
    signature: str = ""
    advertisement_digest: str = ""

    def unsigned(self) -> dict[str, Any]:
        value = asdict(self)
        value.pop("signature", None)
        value.pop("advertisement_digest", None)
        return value

    def sealed(self, signer) -> "NodeDnsAdvertisement":
        body = self.unsigned()
        digest = _digest(body)
        signature = base64.b64encode(signer.sign(_canonical({**body, "advertisement_digest": digest}))).decode("ascii")
        return NodeDnsAdvertisement(**body, signature=signature, advertisement_digest=digest)

    def verify(self, verifier, *, now: int | None = None) -> None:
        now = int(time.time()) if now is None else int(now)
        if not self.node_id or not self.hostname.endswith(".test") or not self.address:
            raise ValueError("node DNS advertisement fields are invalid")
        if self.port < 1 or self.port > 65535 or self.expires_at <= now:
            raise PermissionError("node DNS advertisement is expired or has invalid port")
        if self.advertisement_digest != _digest(self.unsigned()):
            raise ValueError("node DNS advertisement digest mismatch")
        verifier.verify(base64.b64decode(self.signature, validate=True), _canonical({**self.unsigned(), "advertisement_digest": self.advertisement_digest}))


class ServicePublicationController:
    """Publishes only healthy service endpoints and verified, unexpired nodes."""

    def __init__(self, registry: ServiceRegistry, root: Path | str):
        self.registry = registry
        self.root = Path(root)
        self._loopback_opener = build_opener(ProxyHandler({}))

    def stage(self, health: Mapping[str, str] | None = None) -> dict[str, Any]:
        health = health or {}
        services = self.registry.snapshot()
        enabled: dict[str, Mapping[str, Any]] = {}
        suppressed: dict[str, str] = {}
        for name, config in services.items():
            status = str(health.get(name, "unprobed"))
            if config["enabled"] and status == "healthy":
                enabled[name] = config
            else:
                suppressed[name] = status if config["enabled"] else "disabled"
        rendered = ServiceRegistry(enabled, reverse_proxy_port=self.registry.reverse_proxy_port) if enabled else None
        return {
            "beast_object_type": "service_publication_stage",
            "registry_digest": self.registry.digest(),
            "published_services": sorted(enabled),
            "suppressed_services": suppressed,
            "hosts": rendered.hosts_entries() if rendered else "# Generated by BEAST; no healthy services.\n",
            "proxy_config": rendered.nginx_config() if rendered else "# Generated by BEAST; no healthy services.\n",
        }

    def publish(self, health: Mapping[str, str] | None = None, *, nodes: tuple[NodeDnsAdvertisement, ...] = (), verifier=None, now: int | None = None) -> dict[str, Any]:
        stage = self.stage(health)
        zone_rows = ["$ORIGIN beast.test.", "$TTL 30", "@ IN SOA ns.beast.test. hostmaster.beast.test. 1 60 30 300 30", "@ IN NS ns.beast.test."]
        for node in nodes:
            if verifier is None:
                raise PermissionError("cryptographic node DNS publication requires a verifier")
            node.verify(verifier, now=now)
            host = node.hostname.removesuffix(".test") + "."
            zone_rows.append(f"{host} IN A {node.address}")
            zone_rows.append(f"{host} IN TXT \"beast-node={node.node_id};key={node.key_id};digest={node.advertisement_digest}\"")
        output = self.root / "generated"
        _atomic(output / "hosts.generated", stage["hosts"])
        _atomic(output / "nginx.generated.conf", stage["proxy_config"])
        _atomic(output / "beast.test.zone", "\n".join(zone_rows) + "\n")
        receipt = {key: value for key, value in stage.items() if key not in {"hosts", "proxy_config"}}
        receipt.update({
            "node_count": len(nodes),
            "output_dir": str(output),
            "health": {str(name): str(status) for name, status in (health or {}).items()},
        })
        receipt["publication_digest"] = _digest(receipt)
        _atomic(output / "publication.receipt.json", json.dumps(receipt, sort_keys=True, indent=2) + "\n")
        return receipt

    def reconcile(self, *, timeout_seconds: float = 1.5) -> dict[str, Any]:
        """Probe declared loopback health contracts, then atomically publish the result."""
        health: dict[str, str] = {}
        for name, service in self.registry.services.items():
            if not service.enabled:
                health[name] = "disabled"
                continue
            try:
                with self._loopback_opener.open(
                    f"http://{service.upstream}{service.health_path}", timeout=max(0.1, timeout_seconds)
                ) as response:
                    health[name] = "healthy" if 200 <= response.status < 400 else "unhealthy"
            except (OSError, URLError, ValueError):
                health[name] = "unhealthy"
        receipt = self.publish(health)
        return {**receipt, "health": health, "reconciled": True}
