const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('beastDesktop', {
  status: () => ipcRenderer.invoke('beast:status'),
  listFiles: (workspace, limit) => ipcRenderer.invoke('beast:list-files', workspace, limit),
  readFile: (workspace, path, maxChars) => ipcRenderer.invoke('beast:read-file', workspace, path, maxChars),
  listTargetFiles: payload => ipcRenderer.invoke('beast:workspace-target-list-files', payload),
  readTargetFile: payload => ipcRenderer.invoke('beast:workspace-target-read-file', payload),
  writeTargetFile: payload => ipcRenderer.invoke('beast:workspace-target-write-file', payload),
  searchWorkspace: payload => ipcRenderer.invoke('beast:workspace-search', payload),
  replaceWorkspace: payload => ipcRenderer.invoke('beast:workspace-replace', payload),
  workspaceGitStatus: payload => ipcRenderer.invoke('beast:workspace-git-status',payload),
  workspaceGitRepositories: () => ipcRenderer.invoke('beast:workspace-git-repositories'),
  workspaceGitAction: payload => ipcRenderer.invoke('beast:workspace-git-action', payload),
  workspaceGitDiff: payload => ipcRenderer.invoke('beast:workspace-git-diff', payload),
  workspaceGitCommit: payload => ipcRenderer.invoke('beast:workspace-git-commit', payload),
  workspaceGitBranch: payload => ipcRenderer.invoke('beast:workspace-git-branch', payload),
  workspaceGitHunks: payload => ipcRenderer.invoke('beast:workspace-git-hunks', payload),
  workspaceGitHunkAction: payload => ipcRenderer.invoke('beast:workspace-git-hunk-action', payload),
  workspaceGitConflict: payload => ipcRenderer.invoke('beast:workspace-git-conflict', payload),
  workspaceGitResolve: payload => ipcRenderer.invoke('beast:workspace-git-resolve', payload),
  workspaceGitHistory: payload => ipcRenderer.invoke('beast:workspace-git-history', payload),
  workspaceGitRemotes: payload => ipcRenderer.invoke('beast:workspace-git-remotes',payload),
  workspaceGitOperation: payload => ipcRenderer.invoke('beast:workspace-git-operation', payload),
  workspaceTasks: payload => ipcRenderer.invoke('beast:workspace-tasks',payload),
  runWorkspaceTask: payload => ipcRenderer.invoke('beast:workspace-task-run', payload),
  workspaceSettings: payload => ipcRenderer.invoke('beast:workspace-settings',payload),
  saveWorkspaceSettings: payload => ipcRenderer.invoke('beast:workspace-settings-save',payload),
  workspaceTests: payload => ipcRenderer.invoke('beast:workspace-tests',payload),
  runWorkspaceTest: payload => ipcRenderer.invoke('beast:workspace-test-run',payload),
  listWorkspaceTaskSessions: () => ipcRenderer.invoke('beast:workspace-task-list'),
  startWorkspaceTask: payload => ipcRenderer.invoke('beast:workspace-task-start', payload),
  stopWorkspaceTask: id => ipcRenderer.invoke('beast:workspace-task-stop', id),
  fileOperation: (workspace, operation) => ipcRenderer.invoke('beast:file-operation', workspace, operation),
  openWorkspaceWindow: workspace => ipcRenderer.invoke('beast:open-workspace-window', workspace),
  releaseReadiness: workspace => ipcRenderer.invoke('beast:release-readiness', workspace),
  toolingSnapshot: (workspace, activeFile) => ipcRenderer.invoke('beast:tooling-snapshot', workspace, activeFile),
  systemSnapshot: workspace => ipcRenderer.invoke('beast:system-snapshot', workspace),
  listExecutionTargets: payload => ipcRenderer.invoke('beast:execution-target-list', payload),
  getExecutionTarget: () => ipcRenderer.invoke('beast:execution-target-get'),
  setExecutionTarget: payload => ipcRenderer.invoke('beast:execution-target-set', payload),
  ideCompatibility: workspace => ipcRenderer.invoke('beast:ide-compatibility', workspace),
  installIdeCapability: options => ipcRenderer.invoke('beast:ide-capability-install', options),
  startIdeProtocol: options => ipcRenderer.invoke('beast:ide-protocol-start', options),
  requestIdeProtocol: payload => ipcRenderer.invoke('beast:ide-protocol-request', payload),
  notifyIdeProtocol: payload => ipcRenderer.invoke('beast:ide-protocol-notify', payload),
  stopIdeProtocol: sessionId => ipcRenderer.invoke('beast:ide-protocol-stop', sessionId),
  executeNotebookCell: payload => ipcRenderer.invoke('beast:notebook-execute', payload),
  startNotebookKernel: root => ipcRenderer.invoke('beast:notebook-kernel-start', root),
  requestNotebookKernel: payload => ipcRenderer.invoke('beast:notebook-kernel-request', payload),
  stopNotebookKernel: () => ipcRenderer.invoke('beast:notebook-kernel-stop'),
  probeRemote: payload => ipcRenderer.invoke('beast:remote-probe', payload),
  listRemoteFiles: payload => ipcRenderer.invoke('beast:remote-list-files', payload),
  searchRemoteWorkspace: payload => ipcRenderer.invoke('beast:remote-search', payload),
  reconnectRemote: () => ipcRenderer.invoke('beast:remote-reconnect'),
  readRemoteFile: payload => ipcRenderer.invoke('beast:remote-read-file', payload),
  writeRemoteFile: payload => ipcRenderer.invoke('beast:remote-write-file', payload),
  runRemoteTerminal: payload => ipcRenderer.invoke('beast:remote-terminal-run', payload),
  inspectDevContainers: payload => ipcRenderer.invoke('beast:dev-container-inspect', payload),
  startDevContainer: payload => ipcRenderer.invoke('beast:dev-container-start', payload),
  stopDevContainer: payload => ipcRenderer.invoke('beast:dev-container-stop', payload),
  attachDevContainer: payload => ipcRenderer.invoke('beast:dev-container-attach', payload),
  rebuildDevContainer: payload => ipcRenderer.invoke('beast:dev-container-rebuild', payload),
  devContainerLogs: payload => ipcRenderer.invoke('beast:dev-container-logs', payload),
  runDevContainerTerminal: payload => ipcRenderer.invoke('beast:dev-container-terminal-run', payload),
  listRemoteTerminals: () => ipcRenderer.invoke('beast:remote-terminal-list'),
  startRemoteTerminal: payload => ipcRenderer.invoke('beast:remote-terminal-start', payload),
  sendRemoteTerminal: payload => ipcRenderer.invoke('beast:remote-terminal-send', payload),
  stopRemoteTerminal: id => ipcRenderer.invoke('beast:remote-terminal-stop', id),
  listTerminalSessions: () => ipcRenderer.invoke('beast:terminal-session-list'),
  startTerminalSession: payload => ipcRenderer.invoke('beast:terminal-session-start', payload),
  sendTerminalSession: payload => ipcRenderer.invoke('beast:terminal-session-send', payload),
  stopTerminalSession: id => ipcRenderer.invoke('beast:terminal-session-stop', id),
  listRemoteForwards: () => ipcRenderer.invoke('beast:remote-forward-list'),
  startRemoteForward: payload => ipcRenderer.invoke('beast:remote-forward-start', payload),
  stopRemoteForward: id => ipcRenderer.invoke('beast:remote-forward-stop', id),
  discoverExtensions: root => ipcRenderer.invoke('beast:extension-host-discover', root),
  grantExtensionCapabilities: payload => ipcRenderer.invoke('beast:extension-host-grant', payload),
  setExtensionEnabled: payload => ipcRenderer.invoke('beast:extension-host-enable', payload),
  installWorkspaceExtension: () => ipcRenderer.invoke('beast:extension-host-install'),
  uninstallWorkspaceExtension: payload => ipcRenderer.invoke('beast:extension-host-uninstall', payload),
  executeExtensionCommand: payload => ipcRenderer.invoke('beast:extension-host-execute', payload),
  stopExtensionHost: () => ipcRenderer.invoke('beast:extension-host-stop'),
  chooseWorkspace: () => ipcRenderer.invoke('beast:choose-workspace'),
  workspaceFolders: () => ipcRenderer.invoke('beast:workspace-folders'),
  addWorkspaceFolder: () => ipcRenderer.invoke('beast:workspace-folder-add'),
  removeWorkspaceFolder: id => ipcRenderer.invoke('beast:workspace-folder-remove', id),
  getZoom: () => ipcRenderer.invoke('beast:zoom-get'),
  setZoom: level => ipcRenderer.invoke('beast:zoom-set', level),
  resetZoom: () => ipcRenderer.invoke('beast:zoom-reset'),
  restartGateway: () => ipcRenderer.invoke('beast:restart-gateway'),
  openGateway: () => ipcRenderer.invoke('beast:open-gateway'),
  gatewayRequest: request => ipcRenderer.invoke('beast:gateway-request', request),
  gatewayStreamStart: request => ipcRenderer.invoke('beast:gateway-stream-start', request),
  gatewayStreamStop: id => ipcRenderer.invoke('beast:gateway-stream-stop', id),
  onGatewayLog: callback => ipcRenderer.on('beast:gateway-log', (_event, log) => callback(log)),
  onGatewayStreamMessage: callback => {
    const listener = (_event, message) => callback(message);
    ipcRenderer.on('beast:gateway-stream-message', listener);
    return () => ipcRenderer.removeListener('beast:gateway-stream-message', listener);
  },
  onDesktopVersion: callback => ipcRenderer.on('beast:desktop-version', (_event, info) => callback(info)),
  onWorkspaceSelected: callback => ipcRenderer.on('beast:workspace-selected', (_event, workspace) => callback(workspace)),
  onRefresh: callback => ipcRenderer.on('beast:refresh', () => callback()),
  onIdeProtocolMessage: callback => ipcRenderer.on('beast:ide-protocol-message', (_event, message) => callback(message)),
  onNotebookKernelMessage: callback => ipcRenderer.on('beast:notebook-kernel-message', (_event, message) => callback(message)),
  onRemoteForwardMessage: callback => ipcRenderer.on('beast:remote-forward-message', (_event, message) => callback(message)),
  onRemoteTerminalMessage: callback => ipcRenderer.on('beast:remote-terminal-message', (_event, message) => callback(message)),
  onTerminalSessionMessage: callback => ipcRenderer.on('beast:terminal-session-message', (_event, message) => callback(message)),
  onWorkspaceTaskMessage: callback => ipcRenderer.on('beast:workspace-task-message', (_event, message) => callback(message)),
  onExtensionHostMessage: callback => ipcRenderer.on('beast:extension-host-message', (_event, message) => callback(message)),
});
