(() => {
const release={version:'3.1.0-rc3',build:'BEAST-IDE-3.1.0-RC3'};
const pages=["studio", "workspace", "source", "mission", "models", "agents", "review", "trust", "memory", "evidence", "crystallization", "map", "terminal", "tooling", "doctor", "providers", "system", "worktrees", "deploy", "chronicle", "economy", "settings"];
const core=['studio','workspace','source','models','agents','trust','memory','terminal','settings'];
const profiles=[["1920\u00d71080 at 100%", 1920, 1080], ["1600\u00d7900 at 100%", 1600, 900], ["1366\u00d7768 at 100%", 1366, 768], ["1920\u00d71080 equivalent at 125%", 1536, 864], ["1920\u00d71080 equivalent at 150%", 1280, 720]];
let results=[];const frame=document.getElementById('testFrame'),status=document.getElementById('status'),out=document.getElementById('output'),summary=document.getElementById('summary');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function test(page,profile){const[label,w,h]=profile;frame.style.width=w+'px';frame.style.height=h+'px';frame.src=`../index.html?capture=1&page=${page}&releaseTest=1&t=${Date.now()}`;await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('load timeout')),15000);frame.onload=()=>{clearTimeout(timer);resolve();};});await sleep(1500);const d=frame.contentDocument,win=frame.contentWindow,body=d.body,outlet=d.getElementById('beastPageOutlet');const ids=[...d.querySelectorAll('[id]')].map(n=>n.id),dupes=ids.filter((id,i)=>ids.indexOf(id)!==i);const visible=e=>{const s=win.getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0;};const tiny=[...d.querySelectorAll('p,small,button,label,td,th,.beast-meta,.tiny')].filter(visible).map(e=>({text:(e.textContent||'').trim().slice(0,45),size:parseFloat(win.getComputedStyle(e).fontSize)})).filter(x=>x.size<11);const badTargets=[...d.querySelectorAll('button,a,input,select')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return{text:(e.textContent||e.getAttribute('aria-label')||'').trim().slice(0,35),w:r.width,h:r.height};}).filter(x=>x.h<32||x.w<24);const title=d.querySelector('.beast-page-head h2');return{page,profile:label,width:w,height:h,release:win.BEAST_RELEASE?.version||'',bootError:body.dataset.bootError||'',ownership:body.dataset.releaseOwnership||'',pageRoots:outlet?[...outlet.children].filter(n=>n.classList.contains('beast-page')).length:0,documentOverflow:d.documentElement.scrollWidth-d.documentElement.clientWidth,outletOverflow:outlet?outlet.scrollWidth-outlet.clientWidth:0,duplicateIds:[...new Set(dupes)],tinyText:tiny.slice(0,20),smallTargets:badTargets.slice(0,20),titleClipped:title?title.scrollWidth-title.clientWidth:0,performanceTier:body.dataset.performanceTier||'unknown'};}
async function run(list){results=[];out.textContent='';for(const profile of profiles){for(const page of list){status.textContent=`Testing ${page} · ${profile[0]}`;try{const r=await test(page,profile);results.push(r);out.textContent+=JSON.stringify(r)+'\n';}catch(e){results.push({page,profile:profile[0],error:String(e)});}}}render();status.textContent='Complete';}
function bad(r){return r.error||r.bootError||r.release!==release.version||r.ownership==='fault'||r.pageRoots!==1||r.documentOverflow>2||r.duplicateIds?.length;}
function render(){const fails=results.filter(bad);summary.innerHTML=`<h2>${results.length-fails.length}/${results.length} structural tests passed</h2><table><tr><th>Page</th><th>Profile</th><th>Result</th><th>Notes</th></tr>${results.map(r=>`<tr><td>${r.page}</td><td>${r.profile}</td><td class="${bad(r)?'fail':'pass'}">${bad(r)?'FAIL':'PASS'}</td><td>${r.error||`version ${r.release}, roots ${r.pageRoots}, overflow ${r.documentOverflow}px, tiny ${r.tinyText?.length||0}`}</td></tr>`).join('')}</table>`;}
document.getElementById('core').onclick=()=>run(core);document.getElementById('full').onclick=()=>run(pages);document.getElementById('download').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({release,generatedAt:new Date().toISOString(),results},null,2)],{type:'application/json'}));a.download='BEAST_IDE_RC3_RUNTIME_MATRIX.json';a.click();};
})();
