"""Structural contracts for the CPU-first BEAST compute pipeline."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


@runtime_checkable
class KVTransport(Protocol):
    def register_block(self, **kwargs: Any) -> Any: ...
    def lookup(self, model: str, tokenizer: str, prompt_prefix: str, system_prompt: str, **kwargs: Any) -> Any: ...
    def move(self, block_id: str, target_location: Any, target_engine: Any = None) -> bool: ...
    def cleanup(self, force: bool = False) -> List[str]: ...


@runtime_checkable
class ForgeScheduler(Protocol):
    def register_node(self, node_id: str, capabilities: Optional[List[str]] = None) -> Any: ...
    def submit_work(self, work_type: str, repo_path: str, priority: int = 5, deadline: Optional[str] = None) -> Any: ...
    def assign_work(self, node_id: str, max_items: int = 3) -> List[Any]: ...
    def report_work_result(self, schedule_id: str, node_id: str, success: bool, result: Dict[str, Any]) -> bool: ...


@runtime_checkable
class AblationRunner(Protocol):
    def run_ablation(self, candidate_name: str, task_class: str, transform_type: str, **kwargs: Any) -> Any: ...
    def run_batch(self, candidates: List[Dict[str, str]], runs_per_candidate: int = 3, parallel: int = 1) -> Dict[str, Any]: ...
    def export_results(self, path: Optional[Path] = None) -> Dict[str, Any]: ...


@runtime_checkable
class CreditStore(Protocol):
    def store_semantic_result(self, **kwargs: Any) -> Any: ...
    def lookup_reusable_credit(self, task_class: str, **kwargs: Any) -> Any: ...
    def record_credit_reuse(self, credit_id: str) -> Any: ...
    def mark_stale(self, credit_id: str) -> Any: ...

