(() => {
const release={version:'3.1.0-rc4',build:'BEAST-IDE-3.1.0-RC4'};
const pages=['studio','workspace','source','mission','models','agents','review','trust','memory','evidence','crystallization','map','terminal','tooling','doctor','providers','system','worktrees','deploy','chronicle','economy','settings'];
const core=['studio','workspace','source','mission','review','memory','terminal','tooling','settings'];
const profiles=[['1920×1080 at 100%',1920,1080],['1600×900 at 100%',1600,900],['1366×768 at 100%',1366,768],['1920×1080 equivalent at 125%',1536,864],['1920×1080 equivalent at 150%',1280,720]];
let results=[];const frame=document.getElementById('testFrame'),status=document.getElementById('status'),out=document.getElementById('output'),summary=document.getElementById('summary');const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const visible=(win,e)=>{const s=win.getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};
async function test(page,profile){const[label,w,h]=profile;frame.style.width=w+'px';frame.style.height=h+'px';frame.src=`../index.html?capture=1&page=${page}&releaseTest=1&t=${Date.now()}`;await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('load timeout')),20000);frame.onload=()=>{clearTimeout(timer);resolve()}});await sleep(1300);const d=frame.contentDocument,win=frame.contentWindow,body=d.body,outlet=d.getElementById('beastPageOutlet');const ids=[...d.querySelectorAll('[id]')].map(n=>n.id),dupes=[...new Set(ids.filter((id,i)=>ids.indexOf(id)!==i))];const head=d.querySelector('.beast-page-head'),title=head?.querySelector('h2'),actions=head?.querySelector('.beast-page-actions'),tr=title?.getBoundingClientRect(),ar=actions?.getBoundingClientRect();const headOverlap=!!(tr&&ar&&tr.right>ar.left+1&&tr.left<ar.right-1&&tr.bottom>ar.top+1&&tr.top<ar.bottom-1);const tiny=[...d.querySelectorAll('.beast-page *')].filter(e=>visible(win,e)&&(e.textContent||'').trim()&&e.children.length===0&&parseFloat(win.getComputedStyle(e).fontSize)<9).slice(0,20).map(e=>({text:e.textContent.trim().slice(0,50),size:parseFloat(win.getComputedStyle(e).fontSize)}));return{page,profile:label,width:w,height:h,release:win.BEAST_RELEASE?.version||'',bootError:body.dataset.bootError||'',ownership:body.dataset.releaseOwnership||'',pageRoots:outlet?[...outlet.children].filter(n=>n.classList.contains('beast-page')).length:0,documentOverflow:d.documentElement.scrollWidth-d.documentElement.clientWidth,duplicateIds:dupes,tinyText:tiny,headOverlap,visualRunning:!!win.BeastVisualRuntime?.state?.running,performanceTier:body.dataset.performanceTier||win.BeastVisualRuntime?.state?.tier||'unknown'}}
async function run(list){results=[];out.textContent='';for(const profile of profiles){for(const page of list){status.textContent=`Testing ${page} · ${profile[0]}`;try{const r=await test(page,profile);results.push(r);out.textContent+=JSON.stringify(r)+'\n'}catch(e){results.push({page,profile:profile[0],error:String(e)})}}}render();status.textContent='Complete'}
function bad(r){return r.error||r.bootError||r.release!==release.version||r.ownership==='fault'||r.pageRoots!==1||r.documentOverflow>2||r.duplicateIds?.length||r.headOverlap||r.tinyText?.length||!r.visualRunning}
function render(){const fails=results.filter(bad);summary.innerHTML=`<h2>${results.length-fails.length}/${results.length} tests passed</h2><table><tr><th>Page</th><th>Profile</th><th>Result</th><th>Notes</th></tr>${results.map(r=>`<tr><td>${r.page}</td><td>${r.profile}</td><td class="${bad(r)?'fail':'pass'}">${bad(r)?'FAIL':'PASS'}</td><td>${r.error||`version ${r.release}, roots ${r.pageRoots}, overflow ${r.documentOverflow}px, tiny ${r.tinyText?.length||0}, visual ${r.visualRunning}`}</td></tr>`).join('')}</table>`}
document.getElementById('core').onclick=()=>run(core);document.getElementById('full').onclick=()=>run(pages);document.getElementById('download').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({release,generatedAt:new Date().toISOString(),results},null,2)],{type:'application/json'}));a.download='BEAST_IDE_RC4_RUNTIME_MATRIX.json';a.click()};
})();
